[project]
name = "alyx-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyterlab>=4.3.0",
    "one-api>=2.11.0",
    "smbprotocol>=1.14.0",
    "tqdm>=4.66.6",
]
